CREATE DATABASE IF NOT EXISTS COWE
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON COWE.* TO test@localhost IDENTIFIED BY 'test*';

USE COWE;

CREATE TABLE IF NOT EXISTS GET_USER (
  ID_USER INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(50),
  LOGIN_NAME VARCHAR(50),
  PASSWORD VARCHAR(130)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRC_PROCESS_DEFINITION (
  ID_PROCESS_DEFINITION INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30),
  DESCRIPTION VARCHAR(1000),
  VERSION INT(2) NOT NULL DEFAULT 1,
  ACTIVE VARCHAR(1),
  REALIZATION_TERM VARCHAR(30),
  UNIQUE KEY prc_def_uniq_ver (NAME, VERSION),
  UNIQUE KEY prc_def_uniq_act (NAME, ACTIVE)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRT_PROCESS_INSTANCE (
  ID_PROCESS_INSTANCE INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_PROCESS_DEFINITION INT(4) UNSIGNED NOT NULL,
  PROCESS_START DATETIME,
  PROCESS_END DATETIME,
  STATUS VARCHAR(20),
  FOREIGN KEY (ID_PROCESS_DEFINITION) REFERENCES PRC_PROCESS_DEFINITION(ID_PROCESS_DEFINITION),
  INDEX(status)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRT_TASK (
  ID_TASK INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30),
  ID_PROCESS_DEFINITION INT(4) UNSIGNED NOT NULL,
  ID_PARENT_TASK INT(4) UNSIGNED,
  DESCRIPTION VARCHAR(1000),
  REALIZATION_TERM VARCHAR(30),
  FOREIGN KEY (ID_PROCESS_DEFINITION) REFERENCES PRC_PROCESS_DEFINITION(ID_PROCESS_DEFINITION),
  FOREIGN KEY (ID_PARENT_TASK) REFERENCES PRT_TASK(ID_TASK)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRT_TASK_INSTANCE (
  ID_TASK_INSTANCE INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_TASK INT(4) UNSIGNED NOT NULL,
  ID_PROCESS_INSTANCE INT(4) UNSIGNED NOT NULL,
  ID_PARENT_TASK INT(4) UNSIGNED,
  ACTIVE_FROM DATETIME,
  ACTIVE_TO DATETIME,
  ACTIVE_NOW VARCHAR(1) NOT NULL DEFAULT 'N',
  ACTIVE_TIME INT(3),
  STATUS VARCHAR(20),
  ID_USER INT(4) UNSIGNED,
  DESCRIPTION VARCHAR(1000),
  FOREIGN KEY (ID_TASK) REFERENCES PRT_TASK(ID_TASK),
  FOREIGN KEY (ID_PROCESS_INSTANCE) REFERENCES PRT_PROCESS_INSTANCE(ID_PROCESS_INSTANCE),
  FOREIGN KEY (ID_PARENT_TASK) REFERENCES PRT_TASK_INSTANCE(ID_TASK_INSTANCE),
  FOREIGN KEY (ID_USER) REFERENCES GET_USER(ID_USER)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRT_TASK_EDGE (
  ID_TASK_EDGE INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FROM_TASK INT(4) UNSIGNED NOT NULL,
  TO_TASK INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (FROM_TASK) REFERENCES PRT_TASK(ID_TASK),
  FOREIGN KEY (TO_TASK) REFERENCES PRT_TASK(ID_TASK)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRT_TASK_EDGE_INSTANCE (
  ID_TASK_EDGE_INSTANCE INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_TASK_EDGE INT(4) UNSIGNED NOT NULL,
  FROM_TASK INT(4) UNSIGNED NOT NULL,
  TO_TASK INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (ID_TASK_EDGE) REFERENCES PRT_TASK_EDGE(ID_TASK_EDGE),
  FOREIGN KEY (FROM_TASK) REFERENCES PRT_TASK_INSTANCE(ID_TASK),
  FOREIGN KEY (TO_TASK) REFERENCES PRT_TASK_INSTANCE(ID_TASK)
) engine=InnoDB;
